---
title: "Lab_7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load required packages
library(tidyverse)
library(knitr)
#install.packages("nycflights13")
library(nycflights13) 


flights %>% head() %>% kable()
```

Question 1: Compute the average delay by destination, then join on the airports data frame so you can show the spatial distribution of delays. Here’s an easy way to draw a map of the United States:


```{r}
#install.packages("maps")
library(maps) 

airports %>%
  semi_join(flights, c("faa" = "dest")) %>%
  ggplot(aes(lon, lat)) +
    borders("state") +
    geom_point() +
    coord_quickmap()
```


```{r}
#install.packages("maps")
#library(maps) 

airports %>%
  semi_join(flights, c("faa" = "dest")) %>%
  ggplot(aes(lon, lat)) +
    borders("state") +
    geom_point(size=2.5,colour="blue",alpha = 1/5) +
    coord_quickmap()
```

```{r}
avg_delay <- 
  flights%>%
  group_by(dest)%>%
  summarise(mean_delay = mean(arr_delay, na.rm = TRUE))%>%
  inner_join(airports, by = c(dest = "faa"))

avg_delay %>%
  ggplot(aes(lon, lat, colour = mean_delay)) +
  borders("state") +
  geom_point() +
  coord_quickmap()
```
```{r}
avg_dest_delays <-
  flights %>%
  group_by(dest) %>%
  # arrival delay NA's are cancelled flights
  summarise(delay = mean(arr_delay, na.rm = TRUE)) %>%
  inner_join(airports, by = c(dest = "faa"))

avg_dest_delays %>%
  ggplot(aes(lon, lat, colour = delay)) +
  borders("state") +
  geom_point() +
  coord_quickmap()
```

```{r}
planes_info <- inner_join(flights,
                          select(planes,tailnum,year),
                          by = "tailnum",
                          suffix = c("_flight","_plane"))%>%
                          mutate(age=year_flight-year_plane)%>%
                          filter(!is.na(age)) %>%
                          group_by(age) %>%
              summarise(
                dep_delay_mean = mean(dep_delay, na.rm = TRUE),
                arr_delay_mean = mean(arr_delay, na.rm = TRUE)
              )
ggplot(planes_info, aes(x = age, y = dep_delay_mean)) +
  geom_col()
```







